"""Initial migration.

Revision ID: 1619ad8adaec
Revises:
Create Date: 2024-03-25 01:47:35.626365

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1619ad8adaec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_data", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resume_data_first_name"), ["first_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resume_data_last_name"), ["last_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resume_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_data_last_name"))
        batch_op.drop_index(batch_op.f("ix_resume_data_first_name"))

    op.drop_table("resume_data")
    # ### end Alembic commands ###
