"""Add date

Revision ID: 4d55f8fe4d7d
Revises: 1619ad8adaec
Create Date: 2024-03-26 14:07:52.989930

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d55f8fe4d7d"
down_revision = "1619ad8adaec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resume_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.DateTime(), nullable=False))
        batch_op.drop_index("ix_resume_data_first_name")
        batch_op.drop_index("ix_resume_data_last_name")
        batch_op.create_index(
            batch_op.f("ix_resume_data_entry_date"), ["entry_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resume_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_data_entry_date"))
        batch_op.create_index("ix_resume_data_last_name", ["last_name"], unique=False)
        batch_op.create_index("ix_resume_data_first_name", ["first_name"], unique=False)
        batch_op.drop_column("entry_date")

    # ### end Alembic commands ###
