[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
)/
'''

[tool.pytest.ini_options]
addopts = "--cov=app --cov-branch  --cov-report=term-missing --cov-report=html:build/tools/pytest/htmlcov --cov-report=xml:build/tools/pytest/coverage.xml --disable-warnings "
testpaths = ["src/tests"]

[tool.coverage.run]
omit = []
data_file = "build/tools/pytest/.coverage"

[tool.coverage.report]
fail_under = 80
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "raise AssertionError",
    "if 0:",
    "if __name__ == .__main__.:",
]

[tool.pylint]
disable = ["E0401"]
max-line-length = 88
ignore-paths = [".venv/*", "sphinx/*", "src/app/migrations/*"]
source = ["src/app", "src/tests"]
fail-under = 5

[tool.pyright]
venvPath = "."
venv = "venv"
