name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.12

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install -r src/app/app-requirements.txt black pylint pytest pytest-cov coveralls

      - name: Formatter
        run: black --config pyproject.toml src/app src/tests --check

      - name: Linter
        run: pylint --rcfile pyproject.toml src/app src/tests

      - name: Test
        run: pytest

      - name: Coverage Upload
        run: |
          git config --global --add safe.directory /__w/Get-In-The-Mix-Resumes/Get-In-The-Mix-Resumes
          coveralls --rcfile=pyproject.toml --service=github
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
